WebAPP/CoreStructure_APP/CoreStructure_APP/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using CoreStructure_APP.Models;
using CoreStructure_APP.Repository;
using CoreStructure_APP.Utility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreStructure_APP.Controllers
{
    public class QueryController : BaseController
    {
        DropDown_Repository objDrop = new DropDown_Repository();
        Query_Repository objQuery = new Query_Repository();
        Master_Repository objMaster = new Master_Repository();
        private readonly IHostingEnvironment _hostingEnvironment;
        public QueryController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        #region Common Fn
        public IActionResult Index()
        {
            return View();
        }
        private string GetSortOrder(string SortOrder)
        {
            if (SortOrder == null)
            {
                SortOrder = "";
            }
            if (SortOrder != "")
            {
                if (TempData["SortOrder"] != null)
                {
                    string oSortOrder = TempData["SortOrder"].ToString();
                    if (oSortOrder != null)
                    {
                        SortOrder = oSortOrder == "asc" ? "desc" : "asc";
                    }
                }
                TempData["SortOrder"] = SortOrder;
            }
            else
            {
                if (TempData["SortOrder"] != null)
                {
                    SortOrder = TempData["SortOrder"].ToString();
                    TempData["SortOrder"] = SortOrder;
                }
                else
                {
                    SortOrder = "asc";
                    TempData["SortOrder"] = SortOrder;
                }
            }

            return SortOrder;
        }
        private string GetSortCol(string SortCol)
        {
            if (SortCol == null)
            {
                SortCol = "";
            }
            if (SortCol != "")
            {
                ViewData["SortCol"] = SortCol;
            }
            else
            {
                if (ViewData["SortCol"] != null)
                {
                    SortCol = TempData["SortCol"].ToString();
                    ViewData["SortCol"] = SortCol;
                }
            }

            return SortCol;
        }
        #endregion

        #region Query
        public IActionResult AddQuery()
        {
            Query modal = new Query();
            ViewBag.StateList = objDrop.GetStateList(HttpContext.Request.Cookies["Token"].ToString()).results;
            ViewBag.CategoryList = objDrop.GetCategoryList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
            ViewBag.ContactPersonList = objDrop.GetContactPersonList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
            //ViewBag.CityList = "";
            return View(modal);
        }

        [HttpPost]
        [SessionAuthorizeFilter("NewQuery")]
        public ActionResult NewQuery(Query objModel)
        {
            Query model = new Query();
            try
            {
                if (ModelState.IsValid)
                {
                    objModel.OfficeId = Convert.ToInt32(HttpContext.Request.Cookies["OfficeId"].ToString());
                    string result = objQuery.AddNewQuery(objModel, HttpContext.Request.Cookies["Token"].ToString());
                    if (result == "Query Added Successfully..!")
                    {
                        @ViewBag.Message = result;
                        @ViewBag.HideClass = "alert alert-success";
                        ModelState.Clear();
                        ViewBag.StateList = objDrop.GetStateList(HttpContext.Request.Cookies["Token"].ToString()).results;
                        ViewBag.CategoryList = objDrop.GetCategoryList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
                        ViewBag.ContactPersonList = objDrop.GetContactPersonList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
                    }
                    else
                    {
                        @ViewBag.Message = result;
                        @ViewBag.HideClass = "alert alert-danger";
                    }
                }
                else
                {
                    ViewBag.StateList = objDrop.GetStateList(HttpContext.Request.Cookies["Token"].ToString()).results;
                    ViewBag.CategoryList = objDrop.GetCategoryList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
                    ViewBag.ContactPersonList = objDrop.GetContactPersonList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
                    @ViewBag.Message = "Please Fill All Required Fields...!";
                    @ViewBag.HideClass = "alert alert-danger";
                }
            }
            catch (Exception ex)
            {
                ErrorHandler.LogError(ex, HttpContext.Request.Cookies["Token"].ToString(), "WebAPP", "Query/NewQuery");
            }
            return View("AddQuery");
        }

        public IActionResult ManageQuery(Query objMod)
        {
            string sDate = objMod.Date;
            string cName = objMod.CName;
            int sId = objMod.QStatus;
            List<Query> objdatalist = new List<Query>();
            Query modal = new Query();
            int OfficeId = Convert.ToInt32(HttpContext.Request.Cookies["OfficeId"].ToString());
            objdatalist = objQuery.GetQueryList(HttpContext.Request.Cookies["Token"].ToString(), OfficeId);
            if (sId > 0)
            {
                objdatalist = objdatalist.Where(x => x.QStatus == sId).ToList();
            }
            if (!String.IsNullOrEmpty(cName))
            {
                objdatalist = objdatalist.Where(x => x.ClientName.Trim().Contains(cName.Trim())).ToList();
            }
            if (!String.IsNullOrEmpty(sDate))
            {
                DateTime dt = DateTime.Parse(sDate);
                objdatalist = objdatalist.Where(x => DateTime.Parse(x.QueryDate) == dt).ToList();
            }
            ViewBag.QueryList = objdatalist;
            return View(modal);
        }

        public IActionResult EditQuery(int QId)
        {
            Query modal = new Query();
            Query modal1 = new Query();
            int OfficeId = Convert.ToInt32(HttpContext.Request.Cookies["OfficeId"].ToString());
            modal = objQuery.GetQueryList(HttpContext.Request.Cookies["Token"].ToString(), OfficeId).Where(x => x.QId == QId).FirstOrDefault();
            ViewBag.StateList = objDrop.GetStateList(HttpContext.Request.Cookies["Token"].ToString()).results;
            ViewBag.CategoryList = objDrop.GetCategoryList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;
            ViewBag.ContactPersonList = objDrop.GetContactPersonList(HttpContext.Request.Cookies["Token"].ToString(), HttpContext.Request.Cookies["OfficeId"].ToString()).results;

            if (modal != null)
            {
                modal1.QId = QId;
                modal1.ClientName = modal.ClientName;
                modal1.ContactPersonId = modal.ContactPersonId;
                modal1.ContactPersonName = modal.ContactPersonName;
                modal1.QueryDate = Convert.ToDateTime(modal.QueryDate).ToString("yyyy-MM-dd");
                modal1.FatherName = modal.FatherName;
                modal1.MobileNo = modal.MobileNo;
                modal1.EmailId = modal.EmailId;
                modal1.Address = modal.Address;
                modal1.StateId = modal.StateId;
                ViewBag.CityList = objDrop.GetCityListByStateId(modal.StateId, HttpContext.Request.Cookies["Token"].ToString()).results;
                modal1.CityId = modal.CityId;
                modal1.CategoryId = modal.CategoryId;
                modal1.CategoryName = modal.CategoryName;
                modal1.PolicyExpiryDate = modal.PolicyExpiryDate;
                modal1.QuatationAmount = modal.QuatationAmount;
                modal1.Remarks = modal.Remarks;
                modal1.ReferencePerson = modal.ReferencePerson;
                if (!String.IsNullOrEmpty(modal.PolicyExpiryDate))
                {
                    modal1.PolicyExpiryDate = Convert.ToDateTime(modal.PolicyExpiryDate).ToString("yyyy-MM-dd");
                }
                modal1.OfficeId = modal.OfficeId;
            }

            return View(modal1);
        }

        [HttpPost]
        [SessionAuthorizeFilter("UpdateQuery")]
        public ActionResult UpdateQuery(Query objModel)
        {
            Query model = new Query();
            try
            {
                if (ModelState.IsValid)
                {
                    string result = objQuery.UpdateQuery(objModel, HttpContext.Request.Cookies["Token"].ToString());
                    if (result == "Query Details Updated Successfully..!")
                    {
                        @ViewBag.Message = result;
                        @ViewBag.HideClass = "alert alert-success";
                        ModelState.Clear();
                        List<Query> objdatalist = new List<Query>();
                        int OfficeId = Convert.ToInt32(HttpContext.Request.Cookies["OfficeId"].ToString());
                        objdatalist = objQuery.GetQueryList(HttpContext.Request.Cookies["Token"].ToString(), OfficeId);

WebAPP/CoreStructure_APP/CoreStructure_APP/Views/Query/DeletedPolicies.cshtml
@model CoreStructure_APP.Models.Policy_Filter
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewBag.Title = "Deleted Policy";
    ViewBag.Active = "Deleted Policy";
    ViewBag.Open = "Deleted Policy";
    ViewBag.Panel = "Policy";
    ViewData["Title"] = "Deleted Policy";
    Layout = HttpContextAccessor.HttpContext.Request.Cookies["ActiveTheme"];

}

<div class="@ViewBag.HideClass" style="text-align:center" id="success-alert">
    @ViewBag.Message
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="form-group">
                    <div class="col-md-6">
                        <h3 class="panel-title"><strong>Queries</strong></h3>
                    </div>
                    <div class="col-md-6" style="text-align:right;">
                        <button type="button" class="btn btn-info " value="" onclick="location.href = '@Url.Action("AddQuery", "Query") '"><i class="fa fa-list"></i> New Query</button>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <form id="formQuery" asp-controller="Query" asp-action="DeletedPolicies" method="post" class="form-horizontal" enctype="multipart/form-data">
                    <div class="row" style="margin-left:5px !important">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            <label asp-for="FromDate">Date</label>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                                <input type="date" asp-for="FromDate" class="form-control" maxlength="100" autocomplete="off" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            <label asp-for="CategoryId"></label>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-sitemap"></span></span>
                                                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryList">
                                                    <option>---Select Category---</option>
                                                </select>
                                            </div>
                                            <input asp-for="CategoryId" type="hidden" />
                                        </div>
                                    </div>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            <label asp-for="ContactPersonId"></label>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-sitemap"></span></span>
                                                <select asp-for="ContactPersonId" class="form-control" asp-items="ViewBag.ContactPersonList">
                                                    <option>---Select Contact Person---</option>
                                                </select>
                                            </div>
                                            <input asp-for="ContactPersonId" type="hidden" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            <label asp-for="PStatus"></label>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-sitemap"></span></span>
                                                <select asp-for="PStatus" class="form-control">
                                                    <option>---Select Status---</option>
                                                    <option value="1">UnderWritten</option>
                                                    <option value="2">Generated</option>
                                                </select>
                                            </div>
                                            <input asp-for="PStatus" type="hidden" />
                                        </div>
                                    </div>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-10">

                                </div>
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-success"><i class="fa fa-eye"> View</i></button>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                    </div>
                </form>
                <div class="col-md-12">
                    <div class="panel-body">
                        <div class="table-scrollable">
                            <table class="table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer" id="sample_1">
                                <thead>
                                    <tr>
                                        <th>S. No.</th>
                                        <th>Policy Holder</th>
                                        <th>Contact Person</th>
                                        <th>Category</th>
                                        <th>Insurance Company</th>
                                        <th>Subject Insured</th>
                                        <th>Exp. Date</th>
                                        <th>Document</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ int SNo = 0; }
                                    @if (ViewBag.PolicyList != null)
                                    {
                                        foreach (var item in ViewBag.PolicyList)
                                        {
                                            { SNo = SNo + 1; }
                                            <tr>
                                                <td>@SNo<span></span></td>
                                                <td>@item.PolicyHolderName</td>
                                                <td>@item.ContactPersonName</td>
                                                <td>@item.CategoryName</td>
                                                <td>@item.InsuranceCompanyName</td>
                                                <td>@item.SubjectInsured</td>
                                                <td>@item.ExpiryDate</td>
                                                <td>@item.UploadFile</td>
                                                <td>@item.PolicyStatusName</td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="7">No Data Found... </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#sample_1').DataTable({
            rowReorder: {
                selector: 'td:nth-child(2)'
            },
            responsive: true

        });
    });
</script>



<script src="~/Content/datatable/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#sample_1').DataTable({
        });
    });
</script>