WebAPP/CoreStructure_APP/CoreStructure_APP/Controllers/AuthController.cs
using System.Threading.Tasks;
using CoreStructure_APP.Models;
using CoreStructure_APP.Repository;
using CoreStructure_APP.Utility;
//using Doconut.Config;
//using Doconut.Viewer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Data;
using static CoreStructure_APP.Utility.Standard;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.Net;
using System.Text;
using System.Net.NetworkInformation;
using System.Management;
using CoreStructure_API.Utility;

namespace CoreStructure_APP.Controllers
{


    public class AuthController : Controller
    {

        private IHttpContextAccessor _accessor;


        Auth_Repository objAuthRepo = new Auth_Repository();
        Employee_Repository objEmpRepo = new Employee_Repository();
        DropDown_Repository objDropRepo = new DropDown_Repository();
        SubCompany_Repository objSCRepo = new SubCompany_Repository();
        private readonly IHostingEnvironment _hostingEnvironment;
        string baseUrl = APIHelper.BaseURL();

        public AuthController(IHttpContextAccessor accessor, IHostingEnvironment hostingEnvironment)
        {
            _accessor = accessor;
            _hostingEnvironment = hostingEnvironment;
        }

        public string GetIP()
        {
            var ip = _accessor.HttpContext?.Connection?.RemoteIpAddress?.ToString();
            return ip;
        }


        private string GetMacAddress()
        {
            //string macAddresses = string.Empty;
            //foreach (NetworkInterface nic in NetworkInterface.GetAllNetworkInterfaces())
            //{
            //    if (nic.OperationalStatus == OperationalStatus.Up)
            //    {
            //        macAddresses += nic.GetPhysicalAddress().ToString();
            //        break;
            //    }
            //}
            //return macAddresses;

            var mbs = new ManagementObjectSearcher("Select ProcessorId From Win32_processor");
            ManagementObjectCollection mbsList = mbs.Get();
            string id = "";
            foreach (ManagementObject mo in mbsList)
            {
                id = mo["ProcessorId"].ToString();
                break;
            }
            return id;
        }

        #region Login (GET)

        [HttpGet]
        public IActionResult Login()
        {
            foreach (var cookie in Request.Cookies.Keys)
            {
                Response.Cookies.Delete(cookie);
            }
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login(string Returnurl)
        {
            Login_Model pLoginModel = new Login_Model();
            pLoginModel.HDReturnurl = Returnurl;
            return View(pLoginModel);
        }


        [AllowAnonymous]
        public ActionResult TodoLogin(string loginkey)
        {
            string tokenkey = CryptorEngine.Decrypt(loginkey, true);
            string[] cipherString = tokenkey.Split(',');
            
            
            Login_Model objModel = new Login_Model();
            objModel.UserId = Convert.ToInt32(cipherString[0].ToString());
            objModel.Vertical = Convert.ToInt32(cipherString[1].ToString());
            objModel.UserName = "username";
            objModel.Role = 1;
            objModel.Name = "nameofuser";
            //objModel.UserName = cipherString[2].ToString();
            //objModel.Vertical = Convert.ToInt32(cipherString[3].ToString());
            //objModel.Role = Convert.ToInt32(cipherString[4].ToString());
            
            var data = objAuthRepo.CheckLogin(objModel);
            if (data.results.LoginStatus == "Success")
            {
                string logintoken = data.results.UserId.ToString() + "," + data.results.Name.ToString() + "," + data.results.UserName.ToString() + "," + data.results.Vertical.ToString() + "," + data.results.Role.ToString() + "," + "";
                string strCookieValue = CryptorEngine.Encrypt(logintoken, true);
                ViewBag.Tokenkey = strCookieValue;

                CookieOptions option = new CookieOptions();
                option.Expires = DateTime.Now.AddMinutes(60);
                option.IsEssential = true;
                Response.Cookies.Append("Token", strCookieValue, option);
                Response.Cookies.Append("UserId", data.results.UserId.ToString(), option);
                Response.Cookies.Append("UserName", data.results.UserName.ToString(), option);
                Response.Cookies.Append("Role", data.results.Role.ToString(), option);
                Response.Cookies.Append("OfficeId", data.results.OfficeId.ToString(), option);
                Response.Cookies.Append("EmpId", data.results.EmpId.ToString(), option);
                Response.Cookies.Append("Name", data.results.Name.ToString(), option);
                Response.Cookies.Append("Vertical", data.results.Vertical.ToString(), option);
                Response.Cookies.Append("UserMobile", data.results.UserMobile.ToString(), option);
                Response.Cookies.Append("UserEmail", data.results.UserEmail.ToString(), option);
              return  RedirectToAction("Index", "ToDo");

            }
            else
            {

            }

            return View("Login");
        }

        [AllowAnonymous]
        public ActionResult createkey(string Userid, string Name, string Username, string Vertical, string Role)
        {
        
            string token = Userid + "," + Name + "," + Username + "," + Vertical + "," + Role + "," + StandardDateTime.GetDateTime();
            string strCookieValue = CryptorEngine.Encrypt(token, true);
            ViewBag.Tokenkey = strCookieValue;
            return View();
        
        }


        [AllowAnonymous]
        public ActionResult logout()
        {
            try { 

            int vertical = Convert.ToInt32(HttpContext.Request.Cookies["Vertical"].ToString());


            foreach (var cookie in Request.Cookies.Keys)
            {
                Response.Cookies.Delete(cookie);
            }

            if (vertical == 1)
            {
                
                return Redirect("http://erp.vsc.co.in/");
            }
            else if (vertical == 2)
            {

                return Redirect("http://erp.vscconsulting.in/");

            }
            else if (vertical == 3)
            {
                return Redirect("http://erp.pearlinsurancebroker.com/");
            }
            else if (vertical == 4)
            {
                return Redirect("http://erp.pearltechnosolutions.com/");
            }
            else if (vertical == 5)
            {
                return Redirect("http://test.pearlattorneys.in/");
            }
            else
            {
                return Redirect("https://www.vinodsinghal.com/");
            }
            }
            catch(Exception ex)
            {
                

            }

            return View();
        }




        #endregion

        #region Login (POST)

        [HttpPost]
        public JsonResult GetOTPForLogIn(string uName, string pWord)
        {
            string macAdd = GetMacAddress();
            Login_Model objModel = new Login_Model();
            objModel.UserName = uName;
            objModel.Password = pWord;
            objModel.IPAddress = GetIP();
            objModel.MacAddress = GetMacAddress();
            OTP_Return_Value_API modal = new OTP_Return_Value_API();
            modal = objAuthRepo.GetOTPForLogIn(objModel);
            if (modal.results.LoginStatus == "Success")
            {
                if (modal.results.IsSameDevice == 0)
                {
                    if (!String.IsNullOrEmpty(modal.results.MobileNo))
                    {
                        HttpWebResponse response = null;
                        WebRequest request = null;
                        string MsgText = modal.results.return_OTP + " is the OTP for your Pearl Insurance Broker verification. Please DO NOT share your OTP with anyone";

                        string url = "http://msg.msgclub.net/rest/services/sendSMS/sendGroupSms?AUTH_KEY=a07df1e68b3dd146667cfb6a859c213&message=" + Convert.ToString(MsgText) + "&senderId=PRLBKR&routeId=1&mobileNos=" + Convert.ToString(modal.results.MobileNo) + "&smsContentType=english";
                        request = WebRequest.Create(url);
                        response = (HttpWebResponse)request.GetResponse();
                        Stream stream = response.GetResponseStream();
                        Encoding ec = System.Text.Encoding.GetEncoding("utf-8");
                        StreamReader reader = new
                        System.IO.StreamReader(stream, ec);
                        reader.Close();
                        stream.Close();
                    }
                }
            }
            return Json(modal);
        }

        [HttpPost]
        public IActionResult Login(Login_Model objModel)
        {
            string error = "";
            try
            {
                if (objModel.IsSameMac == 1)
                {
                    ModelState.Remove("OTP");
                }
                if (ModelState.IsValid)
                {
                    objModel.IPAddress = GetIP();
                    objModel.MacAddress = GetMacAddress();

                    var data = objAuthRepo.CheckLogin(objModel);
                    error = data.Error;

                    if (data.results.LoginStatus == "Success")
                    {
                        CookieOptions option = new CookieOptions();
                        //HttpContext.Session.SetString("Token", data.results.token);
                        //HttpContext.Session.SetString("ActiveTheme", data.results.theme);

                        option.Expires = DateTime.Now.AddMinutes(30);

WebAPP/CoreStructure_APP/CoreStructure_APP/Views/Shared/_LayoutLogin.cshtml
<!doctype html>
<html class="fixed">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <meta name="keywords" content="PIB || Login" />
    <meta name="description" content="PIB || Login">
    
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Content/Theme2/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Theme2/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/Content/Theme2/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Content/Theme2/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/Theme2/assets/stylesheets/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Content/Theme2/assets/stylesheets/skins/default.css" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Content/Theme2/assets/stylesheets/theme-custom.css">

    <!-- Head Libs -->
    <script src="~/Content/Theme2/assets/vendor/modernizr/modernizr.js"></script>

</head>

@*<body style="background-image:url(../Content/BackImage.jpg);background-repeat: no-repeat;" >*@

<body style="background-image:url(../Content/backImage.png); background-repeat: no-repeat; display:block; width:100%;">

    <!-- start: page -->
    <section class="body-sign">
        @RenderBody()
    </section>
    <!-- end: page -->
    <!-- Vendor -->
    <script src="~/Content/Theme2/assets/vendor/jquery/jquery.js"></script>
    <script src="~/Content/Theme2/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Content/Theme2/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/Theme2/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="~/Content/Theme2/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/Theme2/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="~/Content/Theme2/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Content/Theme2/assets/javascripts/theme.js"></script>

    <!-- Theme Custom -->
    <script src="~/Content/Theme2/assets/javascripts/theme.custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Content/Theme2/assets/javascripts/theme.init.js"></script>






 


</body>
</html>

WebAPP/CoreStructure_APP/CoreStructure_APP/Views/Shared/_LayoutPublic.cshtml
<!DOCTYPE html>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using CoreStructure_APP.Utility
<html lang="en">
<head>
    <!-- META SECTION -->
    <title>PIB - @ViewBag.Title</title>
    @*@{
            string username;
            foreach (var cookie in HttpContextAccessor.HttpContext.Request.Cookies)
            {
                @cookie.Key @cookie.Value

                if (cookie.Key == "UserId")
                {
                    username = cookie.Value;
                }
            }
        }*@
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />



    <style type="text/css">
        @@font-face {
            font-family: 'roboto.regular';
            src: url('Content/roboto.regular.ttf');
        }

        .classname {
            font-family: 'roboto.regular';
        }
    </style>

    @*<a href="~/Content/roboto.regular.ttf">~/Content/roboto.regular.ttf</a>*@

    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <!-- END META SECTION -->
    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="Theme" href="~/Content/Theme1/css/Theme-default.css" />

    <link href="~/Content/CustomCSS/Global.css" rel="stylesheet" />
    <!-- EOF CSS INCLUDE -->
</head>
<body>
    <!-- START PAGE CONTAINER -->
    <div class="page-container">

        <!-- START PAGE SIDEBAR -->
        <div class="page-sidebar">
            <!-- START X-NAVIGATION -->
            <ul class="x-navigation">
                <li class="xn-logo">
                    <a href="@Url.Action("Index", "Home",new { Area=""}, null)" style="height:100% !important"><img src="~/Images/logo-gray.png" style="width:40%;" /></a>
                    <a href="#" class="x-navigation-control"></a>
                </li>
            </ul>


            <!-- END X-NAVIGATION -->
        </div>
        <!-- END PAGE SIDEBAR -->
        <!-- PAGE CONTENT -->
        <div class="page-content">

            <!-- START X-NAVIGATION VERTICAL -->
            <ul class="x-navigation x-navigation-horizontal x-navigation-panel">

                <li class="xn-icon-button" title="minimize / maximize">
                    <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                </li>
                <li class="xn-icon-button pull-right">
                    <a href="http://202.21.32.26:954/DMS/web_help/index.htm" target="_blank" title="help"><span class="fa fa-info"></span></a>
                </li>
            </ul>
            <!-- END X-NAVIGATION VERTICAL -->
            <!-- START BREADCRUMB -->
            <ul class="breadcrumb">
                <li><a href="@Url.Action("Index","Home",new { Area=""}, null)">Home</a></li>
                <li>@ViewBag.Panel</li>
                <li class="active">@ViewBag.Open</li>
            </ul>
            <!-- END BREADCRUMB -->
            <!-- PAGE CONTENT WRAPPER -->
            <div class="page-content-wrap">

                @RenderBody()

            </div>
            <!-- END PAGE CONTENT WRAPPER -->
        </div>
        <!-- END PAGE CONTENT -->
    </div>
    <!-- END PAGE CONTAINER -->
    <!-- MESSAGE BOX-->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
        <div class="mb-container">
            <div class="mb-middle">
                <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                <div class="mb-content">
                    <p>Are you sure you want to log out?</p>
                    <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
                </div>
                <div class="mb-footer">
                    <div class="pull-right">
                        <a href="@Url.Action("Login","Auth",new { Area=""}, null)" class="btn btn-success btn-lg">Yes</a>
                        <button class="btn btn-default btn-lg mb-control-close">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END MESSAGE BOX-->
    <!-- MESSAGE BOX-->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-message">
        <div class="mb-container">
            <div class="mb-middle">
                <div class="mb-title"><span class="fa fa-sign-out"></span> Hello <strong>World</strong> ?</div>
                <div class="mb-content">
                    <p>Are you sure you want to log out?</p>
                    <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
                </div>
                <div class="mb-footer">
                    <div class="pull-right">
                        <a href="#" class="btn btn-default btn-lg mb-control-close">Ok</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END MESSAGE BOX-->
    <!-- START PRELOADS -->
    @*<audio id="audio-alert" src="audio/alert.mp3" preload="auto"></audio>
        <audio id="audio-fail" src="audio/fail.mp3" preload="auto"></audio>*@
    <!-- END PRELOADS -->
    <!-- START SCRIPTS -->
    <!-- START PLUGINS -->
    @*<script type="text/javascript" src="~/Content/Theme1/js/plugins/jquery/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script type="text/javascript" src="~/Content/Theme1/js/plugins/jquery/jquery-ui.min.js"></script>
    @*<script type="text/javascript" src="~/Content/Theme1/js/plugins/bootstrap/bootstrap.min.js"></script>*@
    <!-- END PLUGINS -->
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/dataTables.buttons.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/jszip.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/pdfmake.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/vfs_fonts.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/buttons.html5.min.js"></script>
    <script src="~/Content/Theme1/js/plugins/datatables/buttons.print.min.js"></script>

    <!-- START THIS PAGE PLUGINS-->
    <script type='text/javascript' src='~/Content/Theme1/js/plugins/icheck/icheck.min.js'></script>
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/scrolltotop/scrolltopcontrol.js"></script>

    <script type="text/javascript" src="~/Content/Theme1/js/plugins/morris/raphael-min.js"></script>
    @*<script type="text/javascript" src="~/Content/Theme1/js/plugins/morris/morris.min.js"></script>*@
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/rickshaw/d3.v3.js"></script>
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/rickshaw/rickshaw.min.js"></script>
    <script type='text/javascript' src='~/Content/Theme1/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'></script>
    <script type='text/javascript' src='~/Content/Theme1/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'></script>
    <script type='text/javascript' src='~/Content/Theme1/js/plugins/bootstrap/bootstrap-datepicker.js'></script>
    <script src="~/Content/Theme1/js/plugins/bootstrap/bootstrap-file-input.js"></script>
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/owl/owl.carousel.min.js"></script>

    <script type="text/javascript" src="~/Content/Theme1/js/plugins/moment.min.js"></script>
    <script type="text/javascript" src="~/Content/Theme1/js/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- END THIS PAGE PLUGINS-->
    <!-- START TEMPLATE -->
    <script type="text/javascript" src="~/Content/Theme1/js/settings.js"></script>

    <script type="text/javascript" src="~/Content/Theme1/js/plugins.js"></script>
    <script type="text/javascript" src="~/Content/Theme1/js/actions.js"></script>

    @*<script type="text/javascript" src="~/Content/Theme1/js/demo_dashboard.js"></script>*@
    <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->

    <link rel="stylesheet" type="text/css" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.9.3/css/bootstrap-select.min.css">

    <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.9.3/js/bootstrap-select.min.js"></script>

    <script src="~/js/jquery.steps.js"></script>
    <script src="~/js/site.js"></script>

    <script type="text/javascript">
        $("#success-alert").fadeTo(10000, 500).slideUp(500, function () {
            $("#success-alert").slideUp(500);
        });


        $(function () {
            $('.OnlyNumber').keydown(function (e) {
                if (e.shiftKey || e.ctrlKey || e.altKey) {
                    e.preventDefault();
                } else {
                    var key = e.keyCode;
                    if (!((key == 8) || (key == 46) || (key >= 35 && key <= 40) || (key >= 48 && key <= 57) || (key >= 96 && key <= 105))) {
                        e.preventDefault();
                    }
                }
            });
        });

        $("#success-alert").fadeTo(10000, 500).slideUp(500, function () {
            $("#success-alert").slideUp(500);
        });
    </script>
   
</body>
</html>

WebAPP/CoreStructure_APP/CoreStructure_APP/Views/Shared/_Partial_SearchDoc.cshtml
@using (Html.BeginForm("SearchRecord", "DMS_Reports", FormMethod.Post))
{
    <li class="xn-search" style="text-align:center;">
        <input type="text" name="search" id="searchtext" placeholder="Search..." style="background-color:white; border-color:deeppink;color:black;width:70%;" onkeypress="EnterEvent(event)" />
        <button type="button"  id="BtnSearch" value="">Submit</button>
    </li>


    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">

        $("#BtnSearch").click(function () {
            var stext = $("#searchtext").val();
            if (stext) {
                var url = "/DMS_Reports/SearchRecord?text=" + stext;
                window.location.href = url;
            }
            else {
                alert('Enter Value For Search!');
            }
        });


        function EnterEvent(e) {
            if (e.keyCode === 13) {
                e.preventDefault(); // Ensure it is only this code that rusn

                var stext = $("#searchtext").val();
                if (stext) {
                    var url = "/DMS_Reports/SearchRecord?text=" + stext;
                    window.location.href = url;
                }
                else {
                    alert('Enter Value For Search!');
                }
            }
        }

    </script>
}

WebAPP/CoreStructure_APP/CoreStructure_APP/Views/Shared/_Partial_SearchUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}